SET(CMAKE_SYSTEM_NAME emscripten)
SET(CMAKE_SYSTEM_VERSION 1)
SET(CMAKE_SYSTEM_PROCESSOR asmjs)

SET(CMAKE_C_COMPILER emcc)
SET(CMAKE_CXX_COMPILER em++)
SET(CMAKE_AR emar)
SET(CMAKE_LINKER emcc)

SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
